# Generated by Django 5.2.4 on 2025-07-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expenseDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="income",
            name="incomeDate",
            field=models.DateTimeField(),
        ),
    ]
